### ISSUE TITLE
MXNet reimplement

### ISSUE THREAD

**Issue by clhne** [zhanghang1989/RegNet-Search-PyTorch#7]
Good job, but I have some questions:

1)  It is known to all that FAIR's RegNet source [code](https://github.com/facebookresearch/pycls/blob/ecfb53186b426002020f1a580c3d7d7ad723e283/pycls/models/regnet.py) had released(pycls codebase), so what's the difference ?(RegNet-0.4GF is 0.2% less than official) and why u reimplement ?
2) Have u and your team use MXNet or gluon to implement RegNet? If not, why? Does phenomenon implies Pytorch more usability than MXNet ?

Thanks.

**Comment by zhanghang1989** [comment]
This repo is reimplementing the **search process** of RegNet, instead of simply providing configurations

**Comment by zhanghang1989** [comment]
MXNet is very easy to use. Personally, I have joined another team.

**Comment by clhne** [comment]
Yeah, I have found that you use AutoTorch to implement the search process.

Thanks.
